name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Check Token
        env:
          HF_TOKEN: ${{ secrets.HF_token }}
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "::error::HF_token secret is empty or not found. Please verify you added it in Settings -> Secrets and variables -> Actions."
            exit 1
          else
            echo "HF_token is set."
          fi

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_token }}
        run: git push --force https://user:$HF_TOKEN@huggingface.co/spaces/NotSaradhi14/Sci-Weather HEAD:main
